Add tag name validation to input checks in manual workflow

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -54,6 +54,11 @@ jobs:
             echo Branch ${{ inputs.rcBranch }} does not exist."
             exit 1
           fi
+          # Ensure tag name is valid
+          if [[ ! "${{ inputs.tagName }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
+            echo "Invalid tag name: ${{ inputs.tagName }}"
+            exit 1
+          fi          
           # Ensure the tag does not already exist
           if git tag -l | grep -q "${{ inputs.tagName }}"; then
             echo Tag ${{ inputs.tagName }} already exists."
@@ -92,9 +97,9 @@ jobs:
           git checkout master
           git pull origin master
           git log | head -n 10
-          git merge --no-ff ${{ inputs.rcBranch }} -m "Sync after ${{ inputs.tagName }}" || export MERGE_TO_MASTER_FAILED=TRUE
+          git merge --no-ff ${{ inputs.rcBranch }} -m "Sync after ${{ inputs.tagName }}"
           if [ -n "$MERGE_TO_MASTER_FAILED" ]; then
-            echo Merge to master failed, please resolve conflicts manually."
+            echo "Merge to master failed, please resolve conflicts manually."
             exit -1
           else
             git push origin master
